<a href="https://colab.research.google.com/github/HarshiniAiyyer/ANN_Bitcoin/blob/main/pytorch/PyTorch_Detailed_Tutorial_%23%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors


### Creating Tensors

- Building blocks of DL
- Tensors are created using ```torch.Tensor()```

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

#### Scalar

- No dimensions

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int

scalar.item()

7

#### Vector
- it has magnitude and direction

In [ ]:
#Vector

vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [ ]:
vec.shape


torch.Size([2])

#### Matrix

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[0]

tensor([7, 8])

#### Tensor

In [ ]:
tens = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tens

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tens.shape

torch.Size([1, 3, 3])

We got a single 3x3 shaped tensor.

#### Random Tensors

- NN start with tensors full of random numbers and then adjust those random numbers to represent the data. They are the weights for the NN.

`Start with random numbers -> look at data -. update weights -> look at data -> update`

In [ ]:
rat = torch.rand(3,4)
rat

tensor([[0.4504, 0.9795, 0.4559, 0.8273],
        [0.2061, 0.7055, 0.5542, 0.5347],
        [0.6032, 0.5071, 0.1561, 0.6968]])

In [ ]:
rat.ndim

2

3 x 4 = 12 elements

#### Image Tensors

In [ ]:
imgten = torch.rand(size = (224,224,3)) #h, w, color channels - ideally RGB
imgten

tensor([[[0.8011, 0.6236, 0.1510],
         [0.7920, 0.4583, 0.4187],
         [0.5145, 0.7573, 0.6442],
         ...,
         [0.6465, 0.3216, 0.8360],
         [0.7611, 0.3150, 0.4738],
         [0.7766, 0.1744, 0.4155]],

        [[0.7376, 0.9882, 0.6796],
         [0.1796, 0.0302, 0.6741],
         [0.3114, 0.6044, 0.8367],
         ...,
         [0.5816, 0.8496, 0.8940],
         [0.6146, 0.0398, 0.6098],
         [0.7956, 0.5090, 0.3058]],

        [[0.2094, 0.5000, 0.9179],
         [0.2571, 0.5734, 0.7541],
         [0.1377, 0.2308, 0.6546],
         ...,
         [0.3863, 0.2996, 0.7861],
         [0.4131, 0.8325, 0.9475],
         [0.4059, 0.4517, 0.0996]],

        ...,

        [[0.0538, 0.6163, 0.2696],
         [0.5025, 0.2683, 0.1417],
         [0.4010, 0.4292, 0.7795],
         ...,
         [0.8903, 0.1157, 0.0893],
         [0.0989, 0.9976, 0.5196],
         [0.1748, 0.2450, 0.2552]],

        [[0.9543, 0.2549, 0.4190],
         [0.3828, 0.5145, 0.3534],
         [0.

In [ ]:
torch.rand(size = (3,3))

tensor([[0.7666, 0.5450, 0.0240],
        [0.0064, 0.0793, 0.0517],
        [0.2763, 0.8837, 0.8844]])

#### Zeros and Ones Tensor

- Useful for creating masks for NNs.

In [ ]:
ze = torch.zeros(size = (3,4))
ze

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

IMP -> Default dtype is float32.

#### Arange and Zeros-Like

##### Creating range of tensors and tensors-like

- `range` is deprecated. Use `arange` instead.

- Define a tensor similar to another

In [ ]:
#torch.arange

er = torch.arange(start = 0, end = 10, step = 2)
er

tensor([0, 2, 4, 6, 8])

In [ ]:
#tensors-like
ert = torch.zeros_like(er)
ert

tensor([0, 0, 0, 0, 0])

### Tensor DataTypes

In [ ]:
f32tensor = torch.tensor([3.0,6.0,9.0],
                         dtype = None,
                         device = None, #what device is ur tensor on?
                         requires_grad= False) #tracks gradients

f32tensor

tensor([3., 6., 9.])

**Note: **

If tensors are =>

- Not the right datatype: get datatype by using `tensor.dtype`

- Not right shape, use `tensor.shape`

- Not on the right device, use `tensor.device`


In [ ]:
print(f"Datatype : {rat.dtype}")
print(f'Shape: {rat.shape}')
print(f"Device is on: {rat.device}")

Datatype : torch.float32
Shape: torch.Size([3, 4])
Device is on: cpu


### Manipulating Tensors

- Addition
- Subtraction
- Element Wise Multiplication
- Division
- Matrix Multiplication

In [ ]:
print(torch.matmul(torch.rand(3,2), torch.rand(2,3)).ndim)

2


### Tensor Aggregation (min, max, sum, etc)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.max()

tensor(90)

In [ ]:
x = torch.tensor([10, 5, 20, 8])

# Functional form
max_value_func = torch.max(x)
print(f"Using torch.max(x): {max_value_func}")

# Method form
max_value_method = x.max()
print(f"Using x.max(): {max_value_method}")

Using torch.max(x): 20
Using x.max(): 20


In [ ]:
#mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(10.7500), tensor(10.7500))

#### Argmin(), Argmax(): Find positional min and max of tensors

In [ ]:
#find the position with minimum and maximum value.
#Returns index
x.argmin(), x.argmax()

(tensor(1), tensor(2))

#### Reshaping, stacking, Squeezing and unsqueezing tensors

- reshaping : fixing shapes / dimensions
- view -> return a view of the input tnesor but the same memory as the original tensor
- stacking -> multi tensors on top of the other (vstack) or side by side (hstack)

- squeeze -> removes all 1D from a tensor
- unsqueeze -> add 1D to a target tensor

- permute -> return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

##### Reshape

In [ ]:
#add an extra dimension

xr = x.reshape(1,9)
xr, xr.shape, xr.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

##### View

In [ ]:
z = x.view(1,9)
z.shap

torch.Size([1, 9])

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

##### Stacking

- hstack uses dim = 0,
- vstack uses dim = 1

In [ ]:
xs = torch.stack([x,x,x,x], dim = 1)
xs

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##### Permute

- Used widely with images

In [ ]:
y = torch.rand(2,3,4)
y.size()

torch.Size([2, 3, 4])

In [ ]:
torch.permute(y,(2,0,1)).size()

torch.Size([4, 2, 3])

In [ ]:
xorig = torch.rand(size = (224, 224, 3))

xperm = xorig.permute(2,0,1)  #swaps the position of the axis

print(f"Previous shape: {xorig.shape}")
print(f"New shape: {xperm.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from Tensors)

Indexing with Pytorch is similar to indexing with Numpy.

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
#lets index on the most inner bracket (last dim)
x[0][1][1]

tensor(5)

In [ ]:
# : can also be used to select either row or col
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th and 1st dim but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of 0th and 1st dim but only 1 index of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#get index 0 of the 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#print 3,6,9

x[:,:,2]

tensor([6])

### Pytorch and Numpy

- numpy array to pytorch tensor
```torch.from_numpy(ndarray)```

- pytorch tensor to numpy array ```torch.Tensor.numpy()```

In [ ]:
import torch
import numpy as np

arr = np.arange(1.0,8.0)
tens = torch.from_numpy(arr)
arr, tens

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note:
- dtype of numpy is float64
- dtype of tensor is float32